# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25)),
                ('category', models.IntegerField()),
                ('short', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_nr', models.CharField(max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('reg_date', models.DateField(null=True)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CatCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3, null=True)),
                ('prefix', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CatteryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cattery')),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certName', models.CharField(max_length=10)),
                ('certRank', models.IntegerField()),
                ('neuter', models.BooleanField()),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_nr', models.IntegerField()),
                ('guest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('original_reg_date', models.DateField()),
                ('original_reg_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LitterJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.BooleanField()),
                ('rank', models.IntegerField()),
                ('comment', models.CharField(max_length=2048)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Litter')),
            ],
        ),
        migrations.CreateModel(
            name='LitterNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
                ('judgement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.LitterJudgement')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Microchip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microchip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis', models.BooleanField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, null=True)),
                ('ssn', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=3, null=True)),
                ('phoneNumber', models.CharField(max_length=25, null=True)),
                ('comment', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('orginizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert')),
            ],
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Entry')),
                ('judgement', models.CharField(max_length=10)),
                ('biv', models.BooleanField()),
                ('abs', models.BooleanField()),
                ('comment', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='LitterCat',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Neuter',
            fields=[
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Cat')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='owner',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.AddField(
            model_name='microchip',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.AddField(
            model_name='litterjudgement',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show'),
        ),
        migrations.AddField(
            model_name='litter',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show'),
        ),
        migrations.AddField(
            model_name='judge',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.AddField(
            model_name='import',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='import',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Organization'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='entry',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show'),
        ),
        migrations.AddField(
            model_name='ems',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='ems',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Color'),
        ),
        migrations.AddField(
            model_name='catteryowner',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.AddField(
            model_name='catcert',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='catcert',
            name='cert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert'),
        ),
        migrations.AddField(
            model_name='cat',
            name='cattery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cattery'),
        ),
        migrations.AddField(
            model_name='cat',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dam_children', to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sire_children', to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='judgement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement'),
        ),
        migrations.AddField(
            model_name='littercat',
            name='litter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Litter'),
        ),
        migrations.AlterUniqueTogether(
            name='litter',
            unique_together=set([('show', 'catalog')]),
        ),
        migrations.AddField(
            model_name='judgement',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('show', 'catalog_nr')]),
        ),
        migrations.AddField(
            model_name='catcert',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement'),
        ),
    ]
