# Generated by Django 2.2.5 on 2020-02-18 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import kkidb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=124, unique=True)),
                ('salt', models.CharField(default='-', max_length=256)),
                ('password', models.CharField(default='-', max_length=256)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coreAward', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50, null=True)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=25, unique=True)),
                ('category', models.IntegerField()),
                ('short', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_full', models.CharField(max_length=50, null=True, unique=True)),
                ('reg_nr', models.IntegerField(null=True)),
                ('registration_class', models.CharField(default='', max_length=3, null=True)),
                ('country', models.CharField(default='', max_length=3, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('reg_date', models.DateField(null=True)),
                ('isMale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cattery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registry_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=3, null=True)),
                ('prefix', models.BooleanField()),
                ('email', models.CharField(max_length=1024, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('website', models.CharField(max_length=1024, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('certClass', models.IntegerField()),
                ('neuter', models.BooleanField()),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, unique=True)),
                ('short', models.CharField(max_length=20, unique=True)),
                ('desc', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='LitterJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.BooleanField()),
                ('rank', models.IntegerField()),
                ('comment', models.CharField(max_length=2048)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Litter')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('salt', models.CharField(default='-', max_length=256)),
                ('password', models.CharField(default='-', max_length=256)),
                ('account', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkidb.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short', models.CharField(max_length=15, null=True)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('ssn', models.CharField(max_length=10, null=True, unique=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('postcode', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=3, null=True)),
                ('phoneNumber', models.CharField(max_length=25, null=True)),
                ('comment', models.CharField(max_length=2048, null=True)),
                ('email', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50, null=True)),
                ('visibleToPublic', models.BooleanField(default=True)),
                ('openForRegistration', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Neuter',
            fields=[
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Cat')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=10)),
                ('cert', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert')),
            ],
        ),
        migrations.CreateModel(
            name='showAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('giftYear', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=1024, null=True)),
                ('method', models.CharField(max_length=128)),
                ('uri', models.CharField(default=kkidb.models.Randstring, max_length=6, unique=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='kkidb.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('current', models.BooleanField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Microchip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microchip', models.CharField(max_length=30)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('lastRefresh', models.DateTimeField(null=True)),
                ('expires', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=50)),
                ('cookie', models.CharField(max_length=256, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Account')),
            ],
        ),
        migrations.CreateModel(
            name='LitterNomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
                ('judgement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.LitterJudgement')),
            ],
        ),
        migrations.AddField(
            model_name='litterjudgement',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show'),
        ),
        migrations.AddField(
            model_name='litter',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show'),
        ),
        migrations.AddField(
            model_name='judge',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person'),
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('original_reg_date', models.DateField()),
                ('original_reg_id', models.CharField(max_length=20)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.UserGroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.UserGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_nr', models.IntegerField()),
                ('guest', models.BooleanField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show')),
            ],
            options={
                'unique_together': {('show', 'catalog_nr')},
            },
        ),
        migrations.CreateModel(
            name='EMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Breed')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Color')),
            ],
            options={
                'unique_together': {('breed', 'color')},
            },
        ),
        migrations.CreateModel(
            name='CatteryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cattery')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Person')),
            ],
        ),
        migrations.AddField(
            model_name='cattery',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Organization'),
        ),
        migrations.CreateModel(
            name='CatEms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
                ('ems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.EMS')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='cattery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cattery'),
        ),
        migrations.AddField(
            model_name='cat',
            name='dam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dam_children', to='kkidb.Cat'),
        ),
        migrations.AddField(
            model_name='cat',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kkidb.Organization'),
        ),
        migrations.AddField(
            model_name='cat',
            name='sire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sire_children', to='kkidb.Cat'),
        ),
        migrations.CreateModel(
            name='ShowJudges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show')),
            ],
            options={
                'unique_together': {('show', 'judge')},
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Entry')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
            ],
            options={
                'unique_together': {('entry', 'award')},
            },
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Account')),
            ],
            options={
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Payment')),
            ],
            options={
                'unique_together': {('member', 'payment')},
            },
        ),
        migrations.CreateModel(
            name='LitterCat',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Entry')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Litter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='litter',
            unique_together={('show', 'catalog')},
        ),
        migrations.CreateModel(
            name='Judgement',
            fields=[
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kkidb.Entry')),
                ('judgement', models.CharField(default='', max_length=10)),
                ('biv', models.BooleanField(default=False)),
                ('abs', models.NullBooleanField()),
                ('comment', models.CharField(default='', max_length=2048)),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='CatCert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems', models.CharField(max_length=20, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert')),
                ('judgement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement')),
            ],
        ),
    ]
