# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('lastRefresh', models.DateTimeField(null=True)),
                ('expires', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=50)),
                ('cookie', models.CharField(max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='reg_nr',
        ),
        migrations.AddField(
            model_name='cat',
            name='reg_full',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='salt',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='memberpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Permissions'),
        ),
        migrations.AddField(
            model_name='memberpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member'),
        ),
        migrations.AddField(
            model_name='login_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='memberpermissions',
            unique_together=set([('user', 'permission')]),
        ),
    ]
