# Generated by Django 2.2.5 on 2019-09-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0002_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='country',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='cat',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kkidb.Organization'),
        ),
        migrations.AddField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(default='', max_length=3),
        ),
    ]
