# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0002_auto_20190626_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('giftYear', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=1024, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ShowJudges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='showjudges',
            unique_together=set([('show', 'judge')]),
        ),
    ]
