# Generated by Django 2.2.5 on 2019-09-09 13:39

from django.db import migrations, models
import kkidb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0003_auto_20190905_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='country',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='registration_class',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
