# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0003_auto_20190626_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
