# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0004_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
