# Generated by Django 2.2.5 on 2019-09-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0004_auto_20190909_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uri',
            field=models.CharField(default="nonee", max_length=6),
            preserve_default=False,
        ),
    ]
