# Generated by Django 2.2.5 on 2019-09-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0005_payment_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uri',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
