# Generated by Django 2.2.5 on 2019-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0006_auto_20190909_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='NOT SET', max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='salt',
            field=models.CharField(default='NOT SET', max_length=256),
        ),
    ]
