# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0006_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattery',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Organization'),
        ),
    ]
