# Generated by Django 2.2.5 on 2019-09-10 11:37

from django.db import migrations, models
import kkidb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0007_auto_20190910_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uri',
            field=models.CharField(default=kkidb.models.Randstring, max_length=6, unique=True),
        ),
    ]
