# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0007_cattery_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
