# Generated by Django 2.2.5 on 2019-09-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0008_auto_20190910_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='international',
            field=models.BooleanField(default=True),
        ),
    ]
