# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0009_auto_20190629_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Payment')),
            ],
        ),
    ]
