# Generated by Django 2.2.5 on 2019-09-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0009_show_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='coreAward',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='showAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Award')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Show')),
            ],
        ),
    ]
