# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0010_memberpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='member',
        ),
        migrations.AlterUniqueTogether(
            name='memberpayment',
            unique_together=set([('member', 'payment')]),
        ),
    ]
