# Generated by Django 2.2.5 on 2019-09-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0010_auto_20190916_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='certClass',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='judgement',
            name='comment',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge'),
        ),
        migrations.AlterField(
            model_name='judgement',
            name='judgement',
            field=models.CharField(default='', max_length=10),
        ),
    ]
