# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0011_auto_20190629_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
