# Generated by Django 2.2.5 on 2019-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0011_auto_20190922_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
