# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0012_auto_20190701_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Afi Gamli', max_length=75),
            preserve_default=False,
        ),
    ]
