# Generated by Django 2.2.5 on 2019-10-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0012_award_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomination',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='bis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('entry', 'award')},
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='judgement',
        ),
    ]
