# Generated by Django 2.2.5 on 2019-10-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0013_auto_20191001_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judge'),
        ),
    ]
