# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0014_auto_20190705_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattery',
            name='website',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
