# Generated by Django 2.2.5 on 2019-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0014_auto_20191001_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
