# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0016_cattery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattery',
            name='registry_date',
            field=models.DateField(null=True),
        ),
    ]
