# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-06 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0019_auto_20190706_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
