# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0020_auto_20190706_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='catEms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cat')),
            ],
        ),
        migrations.RemoveField(
            model_name='ems',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='ems',
            name='date',
        ),
        migrations.AddField(
            model_name='ems',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cattery',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='catems',
            name='ems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkidb.EMS'),
        ),
    ]
