# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0021_auto_20190717_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='reg_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='short',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='reg_full',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='short',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='ems',
            unique_together=set([('breed', 'color')]),
        ),
    ]
