# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0022_auto_20190717_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='gender',
            new_name='isMale',
        ),
    ]
