# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0024_auto_20190719_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catcert',
            name='judge',
        ),
        migrations.AddField(
            model_name='catcert',
            name='judgement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement'),
        ),
        migrations.AlterField(
            model_name='catcert',
            name='ems',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
