# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0025_auto_20190721_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuter',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
