# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0026_auto_20190721_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='cert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert'),
        ),
    ]
