# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0027_auto_20190721_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='certName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cert',
            old_name='certRank',
            new_name='rank',
        ),
    ]
