# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0029_auto_20190721_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='cert',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kkidb.Cert'),
        ),
    ]
