# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0030_auto_20190722_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
