# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-28 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0031_auto_20190728_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='orginizer',
            new_name='organizer',
        ),
    ]
