# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0033_show_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='public',
            new_name='visibleToPublic',
        ),
        migrations.AddField(
            model_name='show',
            name='openForRegistration',
            field=models.BooleanField(default=False),
        ),
    ]
