# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-25 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kkidb', '0035_auto_20190825_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='judgement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kkidb.Judgement'),
        ),
    ]
